# Generated by Django 3.2.6 on 2021-08-07 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_url', models.URLField()),
                ('request_uuid', models.UUIDField()),
                ('datetime_taken', models.DateTimeField()),
            ],
        ),
    ]
